{% set version = "0.8" %}

package:
  name: piranha
  version: {{ version }}

source:
  fn: piranha-{{ version }}.tar.gz
  url: https://github.com/bluescarni/piranha/archive/v{{ version }}.tar.gz
  sha256: 649f91ceee56446f903551f0665b8807b833d91fd9622c412eadc95d353ac8e6

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - cmake
    - gmp
    - mpfr
    - boost 1.63.*
    - bzip2 1.0.*
    - zlib 1.2.*
  run:
    - gmp
    - mpfr
    - boost 1.63.*
    - bzip2 1.0.*
    - zlib 1.2.*

test:
  commands:
    - test -f $PREFIX/include/piranha/piranha.hpp

about:
  home: https://github.com/bluescarni/piranha
  license: GPL v3 and LGPL v3
  license_file: COPYING.lgpl3
  summary: 'The Piranha computer algebra system.'

extra:
  recipe-maintainers:
    - isuruf
    - bluescarni
