travis:
  secure:
    BINSTAR_TOKEN: mbcaky5WW8aurONs1W5cuExXXikuGG0zfsazRBTbWrrehxuLV2i2rLF8ll2DuK3T8NhMQMMTRwo0Tm6x0M3bveZ9UdIAFGXusKh9X3WvJUuB6U9HhQLEQQ/nDyPLgyadepqALibH3bcU6Rvdj0w/Jy3ynm+3lsEULNtICRKiqgYmhYztF7aIOY+5TK+O62EEooelB3hyP1M3ce2vmnldJsIkNRT0+Zsbo7svk3l8CXSxMgjkeujjVJCUfV/so7S4aSF0aEtQdZqZXIHNP5ZeefZK61sqH+CD0Nq/Go2Zlyx3S4x3ygCADX91yQc0iZTAGUCY5CxV+ooBFETLvUuwUiXdluoBYR95ScyFlKLUiXdvx7XKxBTQdAgcZltct0QYGq2a/KI1W7nFcpYqLybD6+XL+jh59fWb+2THNeTB4tSvzho+VZakBWttiDgsUWgsWiMUoxhbMzbYLa2KXZz9OtLvFa/RnQ/RjruRqLGRDLLHJ+puSJYGBFykf5BQPgwSWjhe73hjGwC48pPWTplH2U8AlHWZ13xOHSuguNxdo95KCm0zqxyK0wNV7YjmwGs/97jJwTFAxxK+VRir6uRnxSsumRmYLRULKZ7QL5MHaSxeSz76fm2kmciu9uAgFR3ftHd3MIOtmaqMFyO+Y+AAlf2a+jfS5/wFpuZgGG3FGUA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
